### ISSUE TITLE
Cast didn't cast

### ISSUE THREAD

**Issue by robhagopian** [AndrewReitz/never-ending-splendor#46]
Asked it to cast, it beeped on the 'smart' speaker, but kept playing on my phone. Not sure how to diagnose/debug... any thoughts?

Thank you,
Rob

**Comment by robhagopian** [comment]
Possibly related to

https://github.com/AndrewReitz/never-ending-splendor/issues/29

?

**Comment by AndrewReitz** [comment]
once I get #50 in can you give it a try. It's a little wonky if you change between shows but works well otherwise.

**Comment by AndrewReitz** [comment]
Everything seems to be working well now. Please give this a test out on the latest beta (hopefully launched soon) and report back.
