### ISSUE TITLE
Feature request: Android Auto

### ISSUE THREAD

**Issue by robhagopian** [AndrewReitz/never-ending-splendor#47]
It was alluded to in the old project that Android Auto support was added to the framework that the app was built on and the feature just needed to be enabled/tested. Is this true? Is it possible? Is it as easy as it sounded?

Thank you,
Rob

**Comment by AndrewReitz** [comment]
hey @robhagopian sorry I haven't gotten back to you. I never got an email from these posts. 

I've been working a bunch over the last month to bring this app onto the latest and greatest features. Soon we will be using media3 which will make adding this back hopefully a bit easier. I don't have any android auto devices to actually test this out on but will do my best.

**Comment by AndrewReitz** [comment]
Looks like to accomplish this 2 things need to be done.

1. Fully support MediaLibraryService and MediaLibrarySession, currently just `onPlaybackResumption` is supported for chromecast
2. Add an automotive module. These seems easy enough, but can't help feel like the docs are forgetting something.

https://developer.android.com/media/implement/surfaces/cars

**Comment by AndrewReitz** [comment]
Found a way to test on the desktop, everything looks good from here. Please test out the latest beta once it's released (waiting on google reviewers) and let me know.

**Comment by AndrewReitz** [comment]
<img width="790" alt="Screenshot 2024-08-11 at 7 53 24 PM" src="https://github.com/user-attachments/assets/aa39e369-c81b-4d0e-8797-73c08d8e41c2">
